
#################################################
### THIS FILE WAS AUTOGENERATED! DO NOT EDIT! ###
#################################################
# file to edit: dev_nb/integration_and_copy_number_20190709.ipynb

# demo to see convert this cell to script
TEST = 'test1'